/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainPackage;

import java.awt.Window;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.*;
import javax.swing.SwingUtilities;

/**
 *
 * @author danil
 */
public class authForm extends javax.swing.JFrame {

    static String login;
    static String pass;
    private static String flag;
    private static int teacherID;
    private static final String DB_URL = "jdbc:sqlite:teacher.db";
    /**
     * Creates new form authForm
     */
    public authForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        passTextField = new javax.swing.JPasswordField();
        enterButton = new javax.swing.JButton();
        noAccLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Авторизация");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Логин:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Пароль:");

        loginTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        passTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        enterButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enterButton.setText("Войти");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        noAccLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noAccLabel.setText("Нет аккаунта?");
        noAccLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noAccLabelMouseClicked(evt);
            }
        });

        outputLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginTextField)
                    .addComponent(passTextField))
                .addContainerGap())
            .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noAccLabel)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noAccLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noAccLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noAccLabelMouseClicked
        this.dispose();
        regForm reg = new regForm();
        reg.setVisible(true);
    }//GEN-LAST:event_noAccLabelMouseClicked

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        login = loginTextField.getText();
        pass = new String(passTextField.getPassword());
        int hashPass = pass.hashCode();
        if (login.isEmpty() || pass.isEmpty())
        {
            outputLabel.setText("Логин или пароль не могут быть пустыми");
        }
        else
        {
            Auth(login, hashPass);
            currentUser();
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(authForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(authForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(authForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(authForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new authForm().setVisible(true);
            }
        });
    }
    
    public static void Auth(String login, int password)
    {
        String findUser = "SELECT teacher_login FROM Teachers WHERE teacher_login = ? AND teacher_pass = ?";
        try (Connection conn = DriverManager.getConnection(DB_URL);
                PreparedStatement stmt = conn.prepareStatement(findUser))
        {
            String hashPass = String.valueOf(password);
            stmt.setString(1, login);
            stmt.setString(2, hashPass);
            
            try (ResultSet rs = stmt.executeQuery())
            {
                if (rs.next())
                {
                    String updateQuery = "UPDATE Teachers SET is_visible = 1 WHERE teacher_login = ?";
                    try (PreparedStatement updateStmt = conn.prepareStatement(updateQuery))
                    {
                        updateStmt.setString(1, login);
                        updateStmt.executeUpdate();
                    }
                    
                    SwingUtilities.invokeLater(() -> {
                    for (Window window : Window.getWindows()) {
                        if (window.isVisible() && window instanceof authForm) {
                            window.dispose();
                            break;
                            }
                        }
                    });
                    openNext();
                    
                }
                else
                {
                    outputLabel.setText("Неверный логин или пароль");
                }
            }
        }
        catch (SQLException ex)
        {
            outputLabel.setText("Ошибка подключения к базе данных");
            ex.printStackTrace();
        }
    }
    
    private static void openNext()
    {
        FirstAppPageForm firstPage = new FirstAppPageForm();
        firstPage.setVisible(true);
    }
    
    private static void currentUser()
    {
        String curUser = "SELECT teacher_login, teacher_id FROM Teachers WHERE teacher_login = ?";
        try (Connection connection = DriverManager.getConnection(DB_URL);
                PreparedStatement stm = connection.prepareStatement(curUser))
        {
            stm.setString(1, login);
            try (ResultSet rs = stm.executeQuery())
            {
                if(rs.next())
                {
                    flag = rs.getString("teacher_login");
                    teacherID = rs.getInt("teacher_id");
                }
            }
        }
        catch (SQLException exc)
        {
            exc.printStackTrace();
        }
    }
    public static String getLogin() {
        return login;
    }

    public static void setLogin(String login) {
        authForm.login = login;
    }
    public static String getFlag()
    {
        return flag;
    }
    public static void setFlag(String flag)
    {
        authForm.flag = flag;
    }
    public static int getTeacherID()
    {
        return teacherID;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JTextField loginTextField;
    private javax.swing.JLabel noAccLabel;
    private static javax.swing.JLabel outputLabel;
    private javax.swing.JPasswordField passTextField;
    // End of variables declaration//GEN-END:variables
}
