/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author danil
 */
public class chooseRoleForm extends javax.swing.JFrame {

    /**
     * Creates new form chooseRoleForm
     */
    public chooseRoleForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentButton = new javax.swing.JButton();
        teacherButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>\n<b>Добро пожаловать\n<br>Выберите роль</b>\n</html>");

        studentButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentButton.setText("Студент");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });

        teacherButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        teacherButton.setText("Преподаватель");
        teacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacherButton))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(studentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        this.dispose();
        FirstAppPageForm content = new FirstAppPageForm();
        content.setVisible(true);
        authForm auth = new authForm();
        auth.setLogin("");
    }//GEN-LAST:event_studentButtonActionPerformed

    private void teacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherButtonActionPerformed
        CreateTeacherDB();
        this.dispose();
        authForm auth = new authForm();
        auth.setVisible(true);
    }//GEN-LAST:event_teacherButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseRoleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseRoleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseRoleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseRoleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseRoleForm().setVisible(true);
            }
        });
    }
    

    public static void CreateTeacherDB()
    {
        Connection conn = null;
        Statement stmt = null;
        try
        {
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection("jdbc:sqlite:teacher.db");
            stmt = conn.createStatement();
            String createTeacherTable = "CREATE TABLE IF NOT EXISTS Teachers" +
            "(" +
            "  teacher_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT," +
            "  teacher_login TEXT NOT NULL," +
            "  teacher_lastname TEXT NOT NULL," +
            "  teacher_initials TEXT NOT NULL," +
            "  teacher_pass TEXT NOT NULL," +
            "  is_visible INTEGER DEFAULT 1" +
            ")";
            stmt.executeUpdate(createTeacherTable);
            String createThemesTable = "CREATE TABLE IF NOT EXISTS Themes" +
            "(" +
            "  theme_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT," +
            "  theme_name TEXT NOT NULL," +
            "  theme_owner TEXT NOT NULL," +
            "  teacher_id INTEGER NOT NULL," +
            "  teacher_login TEXT NOT NULL," +
            "    FOREIGN KEY (teacher_id, teacher_login)" +
            "    REFERENCES Teachers (teacher_id, teacher_login)" +
            ")";
            stmt.executeUpdate(createThemesTable);
            String createContentTable = "CREATE TABLE IF NOT EXISTS Content" +
            "(" +
            "  content_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT," +
            "  content_text TEXT," +
            "  content_image blob," +
            "  theme_id INTEGER NOT NULL," +
            "  teacher_id INTEGER NOT NULL," +
            "    FOREIGN KEY (theme_id, teacher_id)" +
            "    REFERENCES Themes (theme_id, teacher_id)" +
            ")";
            stmt.executeUpdate(createContentTable);
            stmt.close();
            conn.close();
        }
        catch (Exception e)
        {
            e.getStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton teacherButton;
    // End of variables declaration//GEN-END:variables
}
