package mainPackage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Danil
 */
public class FirstTestForm extends javax.swing.JFrame {

    /**
     * Creates new form FirstTestForm
     */
    public FirstTestForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstQuestButtonGroup = new javax.swing.ButtonGroup();
        secondQuestButtonGroup = new javax.swing.ButtonGroup();
        testLabel = new javax.swing.JLabel();
        firstQuestLabel = new javax.swing.JLabel();
        firstAnsFirstQuestButton = new javax.swing.JRadioButton();
        secondAnsFirstQuestButton = new javax.swing.JRadioButton();
        thirdAnsFirstQuestButton = new javax.swing.JRadioButton();
        secondQuestLabel = new javax.swing.JLabel();
        firstAnsSecondQuestButton = new javax.swing.JRadioButton();
        secondAnsSecondQuestButton = new javax.swing.JRadioButton();
        thirdAnsSecondQuestButton = new javax.swing.JRadioButton();
        acceptButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 150));
        setResizable(false);

        testLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        testLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        testLabel.setText("Тест. Модуль 1. Создание базы данных");

        firstQuestLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstQuestLabel.setText("Вопрос 1. Как открыть консоль PostgreSQL?");

        firstQuestButtonGroup.add(firstAnsFirstQuestButton);
        firstAnsFirstQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstAnsFirstQuestButton.setText("Win + R -> cmd");

        firstQuestButtonGroup.add(secondAnsFirstQuestButton);
        secondAnsFirstQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondAnsFirstQuestButton.setText("Пуск -> Поиск -> Командная строка");

        firstQuestButtonGroup.add(thirdAnsFirstQuestButton);
        thirdAnsFirstQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thirdAnsFirstQuestButton.setText("Пуск -> Поиск -> SQL Shell (psql)");

        secondQuestLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondQuestLabel.setText("Вопрос 2. Какая команда позволяет создать базу данных?");

        secondQuestButtonGroup.add(firstAnsSecondQuestButton);
        firstAnsSecondQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstAnsSecondQuestButton.setText("База данных создаётся только в графическом интерфейсе СУБД");

        secondQuestButtonGroup.add(secondAnsSecondQuestButton);
        secondAnsSecondQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondAnsSecondQuestButton.setText("CREATE DATABASE name;");

        secondQuestButtonGroup.add(thirdAnsSecondQuestButton);
        thirdAnsSecondQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thirdAnsSecondQuestButton.setText("CREATE TABLE name;");

        acceptButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acceptButton.setText("Проверить тест");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nextButton.setText("Перейти к Модуль 2. Создание таблицы");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Назад");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(firstQuestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(firstAnsFirstQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(secondAnsFirstQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(thirdAnsFirstQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(secondQuestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(firstAnsSecondQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addComponent(secondAnsSecondQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(thirdAnsSecondQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(acceptButton)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nextButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstQuestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstAnsFirstQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondAnsFirstQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdAnsFirstQuestButton)
                .addGap(18, 18, 18)
                .addComponent(secondQuestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstAnsSecondQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondAnsSecondQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdAnsSecondQuestButton)
                .addGap(18, 18, 18)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        if (thirdAnsFirstQuestButton.isSelected() && secondAnsSecondQuestButton.isSelected())
        {
            resultLabel.setText("Тест успешно пройден!");
        }
        else
        {
            resultLabel.setText("Попробуйте ещё раз!");
        }
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (resultLabel.getText() == "Тест успешно пройден!")
        {
            this.dispose();
            SecondModuleForm secondModule = new SecondModuleForm();
            secondModule.setVisible(true);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        FirstModuleForm firstModule = new FirstModuleForm();
        firstModule.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstTestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton backButton;
    private static javax.swing.JRadioButton firstAnsFirstQuestButton;
    private static javax.swing.JRadioButton firstAnsSecondQuestButton;
    private static javax.swing.ButtonGroup firstQuestButtonGroup;
    private javax.swing.JLabel firstQuestLabel;
    private javax.swing.JButton nextButton;
    private static javax.swing.JLabel resultLabel;
    private static javax.swing.JRadioButton secondAnsFirstQuestButton;
    private static javax.swing.JRadioButton secondAnsSecondQuestButton;
    private javax.swing.ButtonGroup secondQuestButtonGroup;
    private javax.swing.JLabel secondQuestLabel;
    private javax.swing.JLabel testLabel;
    private static javax.swing.JRadioButton thirdAnsFirstQuestButton;
    private static javax.swing.JRadioButton thirdAnsSecondQuestButton;
    // End of variables declaration//GEN-END:variables
}
