package mainPackage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danil
 */
public class FirstModuleForm extends javax.swing.JFrame {

    /**
     * Creates new form FirstModuleForm
     */
    public FirstModuleForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstModelScrollPane = new javax.swing.JScrollPane();
        FirstModelPanel = new javax.swing.JPanel();
        tablesLabel = new javax.swing.JLabel();
        firstTheoryLabel = new javax.swing.JLabel();
        firstPictureLabel = new javax.swing.JLabel();
        toCreateDBLabel = new javax.swing.JLabel();
        secondScreenshotLabel = new javax.swing.JLabel();
        afterCreateDBLabel = new javax.swing.JLabel();
        thridScreenLabel = new javax.swing.JLabel();
        afterSuccessCreateDBLabel = new javax.swing.JLabel();
        nextModuleButton = new javax.swing.JButton();
        backToFirstPageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 150));
        setSize(new java.awt.Dimension(0, 0));

        FirstModelScrollPane.setPreferredSize(new java.awt.Dimension(502, 500));

        FirstModelPanel.setPreferredSize(new java.awt.Dimension(502, 500));

        tablesLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tablesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tablesLabel.setText("Создание базы данных");
        tablesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        firstTheoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstTheoryLabel.setText("<html>Перед созданием базы данных вам необходимо запустить консоль psql (Пуск->Поиск->SQL Shell (psql)).</html>");

        firstPictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/photo_5285005915868753642_x.jpg"))); // NOI18N

        toCreateDBLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toCreateDBLabel.setText("<html>Для создания базы данных необходимо написать следующую команду:  <br>CREATE DATABASE test; <br>где CREATE DATABASE - команда для создания таблицы; test - название таблицы.</html>");

        secondScreenshotLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondScreenshotLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/5287490674708576736.jpg"))); // NOI18N

        afterCreateDBLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        afterCreateDBLabel.setText("<html>После создания базы данных можно увидеть сообщение о том, что команда сработала - CREATE DATABASE.\n<br>Пояснение: В данном приложении вам не нужно будет создавать базу данных. База данных будет сделана за вас, но таблицы создать всё-таки нужно будет.</html>");

        thridScreenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thridScreenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/5287490674708576738.jpg"))); // NOI18N

        afterSuccessCreateDBLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        afterSuccessCreateDBLabel.setText("После успешного создания базы данных можно перейти к созданию таблиц (Модуль 2. Создание таблиц).");

        nextModuleButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nextModuleButton.setText("Перейти к тесту по Модуль 1. Создания базы данных");
        nextModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextModuleButtonActionPerformed(evt);
            }
        });

        backToFirstPageButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backToFirstPageButton.setText("Вернуться к оглавлению");
        backToFirstPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToFirstPageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FirstModelPanelLayout = new javax.swing.GroupLayout(FirstModelPanel);
        FirstModelPanel.setLayout(FirstModelPanelLayout);
        FirstModelPanelLayout.setHorizontalGroup(
            FirstModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(firstTheoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
            .addComponent(firstPictureLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toCreateDBLabel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(secondScreenshotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterCreateDBLabel)
            .addComponent(thridScreenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FirstModelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToFirstPageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextModuleButton)
                .addContainerGap())
            .addComponent(afterSuccessCreateDBLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FirstModelPanelLayout.setVerticalGroup(
            FirstModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstModelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstTheoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstPictureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toCreateDBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondScreenshotLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterCreateDBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thridScreenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterSuccessCreateDBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FirstModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToFirstPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10622, 10622, 10622))
        );

        FirstModelScrollPane.setViewportView(FirstModelPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstModelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstModelScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToFirstPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToFirstPageButtonActionPerformed
        this.dispose();
        FirstContentForm backToFirstPage = new FirstContentForm();
        backToFirstPage.setVisible(true);
    }//GEN-LAST:event_backToFirstPageButtonActionPerformed

    private void nextModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextModuleButtonActionPerformed
        this.dispose();
        FirstTestForm firstTest = new FirstTestForm();
        firstTest.setVisible(true);
    }//GEN-LAST:event_nextModuleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstModuleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FirstModelPanel;
    private javax.swing.JScrollPane FirstModelScrollPane;
    private javax.swing.JLabel afterCreateDBLabel;
    private javax.swing.JLabel afterSuccessCreateDBLabel;
    private javax.swing.JButton backToFirstPageButton;
    private javax.swing.JLabel firstPictureLabel;
    private javax.swing.JLabel firstTheoryLabel;
    private javax.swing.JButton nextModuleButton;
    private javax.swing.JLabel secondScreenshotLabel;
    private javax.swing.JLabel tablesLabel;
    private javax.swing.JLabel thridScreenLabel;
    private javax.swing.JLabel toCreateDBLabel;
    // End of variables declaration//GEN-END:variables
}
