package mainPackage;


import java.sql.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danil
 */
public class FirstContentForm extends javax.swing.JFrame {

    
    private static final String DB_URL = "jdbc:sqlite:teacher.db";
    /**
     * Creates new form FirstContentForm
     */
    public FirstContentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        firstModuleButton = new javax.swing.JButton();
        secondModuleButton = new javax.swing.JButton();
        thirdModuleButton = new javax.swing.JButton();
        teachersButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 150));

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Назад");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        firstModuleButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstModuleButton.setText("Модуль 1. Создание базы данных");
        firstModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstModuleButtonActionPerformed(evt);
            }
        });

        secondModuleButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondModuleButton.setText("Модуль 2. Создание таблицы");
        secondModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondModuleButtonActionPerformed(evt);
            }
        });

        thirdModuleButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thirdModuleButton.setText("Модуль 3. Заполнение таблицы");
        thirdModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdModuleButtonActionPerformed(evt);
            }
        });

        teachersButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teachersButton.setText("Преподаватели");
        teachersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstModuleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(secondModuleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thirdModuleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teachersButton)
                            .addComponent(backButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(teachersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        FirstAppPageForm backToBegin = new FirstAppPageForm();
        backToBegin.setVisible(true);
        //DeleteSession();
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void firstModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstModuleButtonActionPerformed
        this.dispose();
        FirstModuleForm firstModule = new FirstModuleForm();
        firstModule.setVisible(true);
    }//GEN-LAST:event_firstModuleButtonActionPerformed

    private void secondModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondModuleButtonActionPerformed
        this.dispose();
        SecondModuleForm secondModule = new SecondModuleForm();
        secondModule.setVisible(true);
    }//GEN-LAST:event_secondModuleButtonActionPerformed

    private void thirdModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdModuleButtonActionPerformed
        this.dispose();
        ThirdModuleForm thirdModule = new ThirdModuleForm();
        thirdModule.setVisible(true);
    }//GEN-LAST:event_thirdModuleButtonActionPerformed

    private void teachersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersButtonActionPerformed
        teachersForm teachers = new teachersForm();
        teachers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teachersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstContentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstContentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstContentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstContentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstContentForm().setVisible(true);
            }
        });
    }
    
    private void DeleteSession()
    {
        String clearSession = "DELETE FROM ActiveSession";
        try (Connection conn = DriverManager.getConnection(DB_URL);
                PreparedStatement stmt = conn.prepareStatement(clearSession))
                {
                    try (ResultSet rs = stmt.executeQuery())
                    {
                        if (rs.next())
                        {
                            stmt.executeUpdate();
                        }
                    }
                }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton firstModuleButton;
    private javax.swing.JButton secondModuleButton;
    private javax.swing.JButton teachersButton;
    private javax.swing.JButton thirdModuleButton;
    // End of variables declaration//GEN-END:variables
}
