/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainPackage;

import java.awt.Window;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.*;
import javax.swing.SwingUtilities;

/**
 *
 * @author danil
 */
public class regForm extends javax.swing.JFrame {

    static String login;
    static String lastname;
    static String initials;
    static String pass;

    /**
     * Creates new form regForm
     */
    public regForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        lastnameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        initialsField = new javax.swing.JTextField();
        regButton = new javax.swing.JButton();
        haveAccLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(411, 300));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Регистрация");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Логин:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Фамилия и инициалы: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Пароль: ");

        loginField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lastnameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        passField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        initialsField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        regButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regButton.setText("Зарегестрироваться");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        haveAccLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        haveAccLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        haveAccLabel.setText("Уже есть аккаунт?");
        haveAccLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haveAccLabelMouseClicked(evt);
            }
        });

        outputLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginField)
                    .addComponent(passField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initialsField)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(haveAccLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
            .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(initialsField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(haveAccLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void haveAccLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAccLabelMouseClicked
        this.dispose();
        authForm auth = new authForm();
        auth.setVisible(true);
    }//GEN-LAST:event_haveAccLabelMouseClicked

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        login = loginField.getText();
        lastname = lastnameField.getText();
        initials = initialsField.getText();
        pass = new String(passField.getPassword());
        int hashPass = pass.hashCode();
        if (login.isEmpty() || lastname.isEmpty() || initials.isEmpty() || pass.isEmpty())
        {
            outputLabel.setText("Поля не могут быть пустыми");
        }
        else
        {
            Registration(login, lastname, initials, hashPass);
        }
    }//GEN-LAST:event_regButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regForm().setVisible(true);
            }
        });
    }


    public static void Registration(String login, String lastname, String initials, int password)
    {
        
        if (ifUserExists(login))
        {
            outputLabel.setText("Пользователь с таким логином уже существует");
        }
        else
        {
            String addUser = "INSERT INTO Teachers (teacher_login, teacher_lastname, teacher_initials, teacher_pass) VALUES (?, ?, ?, ?)";
            try (Connection conn = DriverManager.getConnection("jdbc:sqlite:teacher.db");
                    PreparedStatement stmt = conn.prepareStatement(addUser))
            {
                String newPass = String.valueOf(password);
                stmt.setString(1, login);
                stmt.setString(2, lastname);
                stmt.setString(3, initials);
                stmt.setString(4, newPass);
                stmt.executeUpdate();
                SwingUtilities.invokeLater(() -> {
                    for (Window window : Window.getWindows()) {
                        if (window.isVisible() && window instanceof regForm) {
                            window.dispose();
                            break;
                            }
                        }
                    });
                openNext();
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }
             
    }
    private static void openNext()
    {
        authForm auth = new authForm();
        auth.setVisible(true);
    }
    
    public static boolean ifUserExists(String login)
    {
        String query = "SELECT 1 FROM Teachers WHERE teacher_login = ?";
        
        try (Connection conn = DriverManager.getConnection("jdbc:sqlite:teacher.db");
             PreparedStatement stmt = conn.prepareStatement(query))
        {
            stmt.setString(1, login);
            try (ResultSet rs = stmt.executeQuery())
            {
                return rs.next();
            }
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel haveAccLabel;
    private static javax.swing.JTextField initialsField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JTextField lastnameField;
    private static javax.swing.JTextField loginField;
    private static javax.swing.JLabel outputLabel;
    private static javax.swing.JPasswordField passField;
    private javax.swing.JButton regButton;
    // End of variables declaration//GEN-END:variables
}
