package mainPackage;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Danil
 */
public class SecondTestForm extends javax.swing.JFrame {

    /**
     * Creates new form SecondTestForm
     */
    public SecondTestForm() {
        initComponents();
    }
    
    public static void Connect()
    {
        Connection conn = null;
        Statement stmt = null;
        try
        {
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection("jdbc:sqlite:teachmodule.db");
            stmt = conn.createStatement();
            
            String dropTableAuthors = "DROP TABLE Authors";
            stmt.executeUpdate(dropTableAuthors);
            String dropTableBooks = "DROP TABLE Books";
            stmt.executeUpdate(dropTableBooks);
            String dropTableGenres = "DROP TABLE Genres";
            stmt.executeUpdate(dropTableGenres);
            String dropTableReader = "DROP TABLE Reader";
            stmt.executeUpdate(dropTableReader);
            String dropTableBookLoan = "DROP TABLE BookLoan";
            stmt.executeUpdate(dropTableBookLoan);
            String dropTablePublisher = "DROP TABLE Publisher";
            stmt.executeUpdate(dropTablePublisher);
            
            String createAuthorTable = "CREATE TABLE IF NOT EXISTS Authors " + 
                    "(AuthorID INTEGER PRIMARY KEY AUTOINCREMENT, " + 
                    "FirstName TEXT NOT NULL, " + 
                    "LastName TEXT NOT NULL, " + 
                    "BirthDate TEXT, " + 
                    "Country TEXT NOT NULL)";
            stmt.executeUpdate(createAuthorTable);
            String createBookTable = "CREATE TABLE IF NOT EXISTS Books " + 
                    "(BookID INTEGER PRIMARY KEY AUTOINCREMENT, " + 
                    "Title TEXT NOT NULL, " + 
                    "AuthorID INTEGER, " +
                    "GenreID INTEGER, " + 
                    "PublisherID INTEGER, " + 
                    "YearPublished TEXT NOT NULL, " + 
                    "ISBN INTEGER NOT NULL, "
                    + "Quantity INTEGER, "
                    + "FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID), "
                    + "FOREIGN KEY (GenreID) REFERENCES Genres(GenreID), "
                    + "FOREIGN KEY (PublisherID) REFERENCES Publisher(PublisherID))";
            stmt.executeUpdate(createBookTable);
            String createGenreTable = "CREATE TABLE IF NOT EXISTS Genres "
                    + "(GenreID INTEGER PRIMARY KEY AUTOINCREMENT, "
                    + "Name TEXT NOT NULL)";
            stmt.executeUpdate(createGenreTable);
            String createReaderTable = "CREATE TABLE IF NOT EXISTS Reader"
                    + "(ReaderID INTEGER PRIMARY KEY AUTOINCREMENT, "
                    + "FirstName TEXT NOT NULL, "
                    + "LastName TEXT NOT NULL, "
                    + "Adress TEXT NOT NULL, "
                    + "PhoneNumber TEXT NOT NULL, "
                    + "Email TEXT NOT NULL)";
            stmt.executeUpdate(createReaderTable);
            String bookLoanTable = "CREATE TABLE IF NOT EXISTS BookLoan "
                    + "(LoanID INTEGER PRIMARY KEY AUTOINCREMENT, "
                    + "BookID INTEGER, "
                    + "ReaderID INTEGER, "
                    + "LoanDate TEXT NOT NULL, "
                    + "ReturnDate TEXT, "
                    + "Status TEXT NOT NULL, "
                    + "FOREIGN KEY (BookID) REFERENCES Books(BookID),"
                    + "FOREIGN KEY (ReaderID) REFERENCES Readers(ReaderID) )";
            stmt.executeUpdate(bookLoanTable);
            String createPublisherTable = "CREATE TABLE IF NOT EXISTS Publisher"
                    + "(PublisherID INTEGER PRIMARY KEY AUTOINCREMENT, "
                    + "Name TEXT NOT NULL, "
                    + "Adress TEXT NOT NULL, "
                    + "PhoneNumber TEXT NOT NULL)";
            stmt.executeUpdate(createPublisherTable);
            stmt.close();
            conn.close();
        }
        catch (Exception e)
        {
            System.out.println("Ошибка, " + e.getClass().getName() + ": " + e.getMessage());
            return;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstAnsGroup = new javax.swing.ButtonGroup();
        secondAnsGroup = new javax.swing.ButtonGroup();
        secondTestLabel = new javax.swing.JLabel();
        firstQuestionLabel = new javax.swing.JLabel();
        firstAnsFirstQuestButton = new javax.swing.JRadioButton();
        secondAnsFirstQuestButton = new javax.swing.JRadioButton();
        thirdAnsFirstQuestButton = new javax.swing.JRadioButton();
        secondQuestionLabel = new javax.swing.JLabel();
        firstAnsSecondQuestButton = new javax.swing.JRadioButton();
        secondAnsSecondQuestButton = new javax.swing.JRadioButton();
        thirdAnsSecondQuestButton = new javax.swing.JRadioButton();
        fourthAnsSecondQuestButton = new javax.swing.JRadioButton();
        acceptButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        nextModuleButton = new javax.swing.JButton();
        resultTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 150));

        secondTestLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        secondTestLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondTestLabel.setText("Тест. Модуль 2. Создание таблицы");

        firstQuestionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstQuestionLabel.setText("Вопрос 1. Из чего состоят таблицы?");

        firstAnsGroup.add(firstAnsFirstQuestButton);
        firstAnsFirstQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstAnsFirstQuestButton.setText("Из ячеек данных");

        firstAnsGroup.add(secondAnsFirstQuestButton);
        secondAnsFirstQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondAnsFirstQuestButton.setText("Из столбцов и строк");

        firstAnsGroup.add(thirdAnsFirstQuestButton);
        thirdAnsFirstQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thirdAnsFirstQuestButton.setText("Из полей и столбцов");

        secondQuestionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondQuestionLabel.setText("Вопрос 2. Какая команда создаёт таблицу?");

        secondAnsGroup.add(firstAnsSecondQuestButton);
        firstAnsSecondQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstAnsSecondQuestButton.setText("CREATE DATABASE");

        secondAnsGroup.add(secondAnsSecondQuestButton);
        secondAnsSecondQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondAnsSecondQuestButton.setText("DELETE FROM TABLE");

        secondAnsGroup.add(thirdAnsSecondQuestButton);
        thirdAnsSecondQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thirdAnsSecondQuestButton.setText("DROP DATABASE");

        secondAnsGroup.add(fourthAnsSecondQuestButton);
        fourthAnsSecondQuestButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fourthAnsSecondQuestButton.setText("CREATE TABLE");

        acceptButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acceptButton.setText("Проверить тест");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Назад");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextModuleButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nextModuleButton.setText("Перейти к Модуль 3. Заполнение таблицы");
        nextModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextModuleButtonActionPerformed(evt);
            }
        });

        resultTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resultTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(secondTestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addComponent(firstQuestionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(firstAnsFirstQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(secondAnsFirstQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(thirdAnsFirstQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(secondQuestionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(firstAnsSecondQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(secondAnsSecondQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(thirdAnsSecondQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fourthAnsSecondQuestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextModuleButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(acceptButton)
                        .addGap(156, 156, 156))))
            .addComponent(resultTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(secondTestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstQuestionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstAnsFirstQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondAnsFirstQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdAnsFirstQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondQuestionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstAnsSecondQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondAnsSecondQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdAnsSecondQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourthAnsSecondQuestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(nextModuleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        SecondModuleForm secondModule = new SecondModuleForm();
        secondModule.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        if (secondAnsFirstQuestButton.isSelected() && fourthAnsSecondQuestButton.isSelected())
        {
            resultTextLabel.setText("Тест успешно пройден!");
        }
        else
        {
            resultTextLabel.setText("Попробуйте ещё раз!");
        }
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void nextModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextModuleButtonActionPerformed
        if (resultTextLabel.getText() == "Тест успешно пройден!")
        {
            this.dispose();
            ThirdModuleForm thirdModule = new ThirdModuleForm();
            thirdModule.setVisible(true);
            Connect();
        }
        
        
    }//GEN-LAST:event_nextModuleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondTestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton firstAnsFirstQuestButton;
    private javax.swing.ButtonGroup firstAnsGroup;
    private javax.swing.JRadioButton firstAnsSecondQuestButton;
    private javax.swing.JLabel firstQuestionLabel;
    private javax.swing.JRadioButton fourthAnsSecondQuestButton;
    private javax.swing.JButton nextModuleButton;
    private static javax.swing.JLabel resultTextLabel;
    private javax.swing.JRadioButton secondAnsFirstQuestButton;
    private javax.swing.ButtonGroup secondAnsGroup;
    private javax.swing.JRadioButton secondAnsSecondQuestButton;
    private javax.swing.JLabel secondQuestionLabel;
    private javax.swing.JLabel secondTestLabel;
    private javax.swing.JRadioButton thirdAnsFirstQuestButton;
    private javax.swing.JRadioButton thirdAnsSecondQuestButton;
    // End of variables declaration//GEN-END:variables
}
