/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danil
 */
public class FirstModuleForm extends javax.swing.JFrame {

    /**
     * Creates new form FirstModuleForm
     */
    public FirstModuleForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstModelScrollPane = new javax.swing.JScrollPane();
        FirstModelPanel = new javax.swing.JPanel();
        tablesLabel = new javax.swing.JLabel();
        firstTheoryLabel = new javax.swing.JLabel();
        firstPictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 150));
        setSize(new java.awt.Dimension(0, 0));

        FirstModelPanel.setPreferredSize(new java.awt.Dimension(500, 10000));

        tablesLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tablesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tablesLabel.setText("Создание базы данных");
        tablesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        firstTheoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstTheoryLabel.setText("<html>Перед созданием базы данных вам необходимо запустить консоль psql (Пуск->Поиск->SQL Shell (psql)). <br><br>Для создания базы данных необходимо написать следующую команду:  <br>CREATE TABLE test; где test - название базы данных.</html>");

        firstPictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo_5285005915868753642_x.jpg"))); // NOI18N

        javax.swing.GroupLayout FirstModelPanelLayout = new javax.swing.GroupLayout(FirstModelPanel);
        FirstModelPanel.setLayout(FirstModelPanelLayout);
        FirstModelPanelLayout.setHorizontalGroup(
            FirstModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(firstTheoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
            .addComponent(firstPictureLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FirstModelPanelLayout.setVerticalGroup(
            FirstModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstModelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstTheoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstPictureLabel)
                .addGap(10698, 10698, 10698))
        );

        FirstModelScrollPane.setViewportView(FirstModelPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstModelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstModelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstModuleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FirstModelPanel;
    private javax.swing.JScrollPane FirstModelScrollPane;
    private javax.swing.JLabel firstPictureLabel;
    private javax.swing.JLabel firstTheoryLabel;
    private javax.swing.JLabel tablesLabel;
    // End of variables declaration//GEN-END:variables
}
