/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Danil
 */
public class SecondModuleForm extends javax.swing.JFrame {

    /**
     * Creates new form SecondModuleForm
     */
    public SecondModuleForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        firstTheoryLabel = new javax.swing.JLabel();
        createTableLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));

        firstTheoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstTheoryLabel.setText("<html>\n\nВ реляционных СУБД данные представлены в виде <b>таблиц</b>. <br>Таблицы в свою очередь состоят из <b>столбцов</b> и <b>строк</b>.\n<br><b>Столбцы</b> определяют <b>структуру таблицы</b>, а <b>в строках</b> уже хранится <b>информация</b>.\n<br><br>Выберем предметную область - библиотека и создадим таблицу Books.\n<br>Тогда таблица будет иметь следующие поля: \n<br> <b>BookID</b> - уникальный идентификационный номер книги. Это поле будет являться первичным ключом, о которых мы поговорим далее.\n<br> <b>Title</b> - название книги. В этом поле мы будем записывать название книги. Типом данных этого поля будет являться TEXT - стандартный тип данных в СУБД PostgreSQL.\n<br> <b>AuthorID</b> - уникальный идентификационный номер автора книги. Это поле будет являться внешним ключом, о которых мы поговорим далее.\n<br> <b>GenreID</b> - уникальный идентификационный номер жанра книги. Это поле также будет являться внешним ключом, как и поле AuthorID.\n<br> <b>PublisherID</b> - уникальнйы идентификационный номер издательства. Аналогично полю AuthorID - является внешним ключом.\n<br> <b>YearPublished</b> - дата публикации книги. Это поле будет иметь тип данных DATE.\n<br> <b>ISBN</b> - уникальный серийный номер книги. Это поле также, как BookID будет являться уникальным, однако не будет являться первичным ключом. Тип поля - INTEGER.\n<br> <b>Quantity</b> - количество данных книг в библиотеке. Это поле будет иметь тип данных - INTEGER. Аналогично полю ISBN.\n\n</html>");

        createTableLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createTableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createTableLabel.setText("Создание таблицы");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createTableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
            .addComponent(firstTheoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(createTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstTheoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondModuleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondModuleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createTableLabel;
    private javax.swing.JLabel firstTheoryLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
